In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [269]:
df1 = pd.read_csv('data/data_modeling.csv')

In [270]:
df1.head()

,R_fighter,B_fighter,Referee,date,location,Winner,title_bout,weight_class,no_of_rounds,B_current_lose_streak,...,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,Henry Cejudo,Marlon Moraes,Marc Goddard,2019-06-08,"Chicago, Illinois, USA",Red,True,Bantamweight,5,0.0,...,2.0,0.0,0.0,8.0,Orthodox,162.56,162.56,135.0,31.0,32.0
1,Valentina Shevchenko,Jessica Eye,Robert Madrigal,2019-06-08,"Chicago, Illinois, USA",Red,True,Women's Flyweight,5,0.0,...,0.0,2.0,0.0,5.0,Southpaw,165.10,167.64,125.0,32.0,31.0
2,Tony Ferguson,Donald Cerrone,Dan Miragliotta,2019-06-08,"Chicago, Illinois, USA",Red,False,Lightweight,3,0.0,...,3.0,6.0,1.0,14.0,Orthodox,180.34,193.04,155.0,36.0,35.0
3,Jimmie Rivera,Petr Yan,Kevin MacDonald,2019-06-08,"Chicago, Illinois, USA",Blue,False,Bantamweight,3,0.0,...,1.0,0.0,0.0,6.0,Orthodox,162.56,172.72,135.0,26.0,29.0
4,Tai Tuivasa,Blagoy Ivanov,Dan Miragliotta,2019-06-08,"Chicago, Illinois, USA",Blue,False,Heavyweight,3,0.0,...,2.0,0.0,0.0,3.0,Southpaw,187.96,190.50,264.0,32.0,26.0

In [271]:
df1.isnull().sum()

R_fighter       0
B_fighter       0
Referee         0
date            0
location        0
               ..
R_Height_cms    0
R_Reach_cms     0
R_Weight_lbs    0
B_age           0
R_age           0
Length: 145, dtype: int64

In [272]:
df1.shape

(3360, 145)

In [273]:
df1["weight_diff_red-blue"]= df1["R_Weight_lbs"] - df1["B_Weight_lbs"] # Red less o more than Blue

In [274]:
df1["height_diff_red-blue"]= df1["R_Height_cms"] - df1["B_Height_cms"] # Red less o more than Blue

In [300]:
list(df1.columns)

['Winner',
 'title_bout',
 'weight_class',
 'B_avg_BODY_att',
 'B_avg_BODY_landed',
 'B_avg_CLINCH_att',
 'B_avg_CLINCH_landed',
 'B_avg_DISTANCE_att',
 'B_avg_DISTANCE_landed',
 'B_avg_GROUND_att',
 'B_avg_GROUND_landed',
 'B_avg_HEAD_att',
 'B_avg_HEAD_landed',
 'B_avg_KD',
 'B_avg_LEG_att',
 'B_avg_LEG_landed',
 'B_avg_PASS',
 'B_avg_REV',
 'B_avg_SIG_STR_att',
 'B_avg_SIG_STR_landed',
 'B_avg_SIG_STR_pct',
 'B_avg_SUB_ATT',
 'B_avg_TD_att',
 'B_avg_TD_landed',
 'B_avg_TD_pct',
 'B_avg_TOTAL_STR_att',
 'B_avg_TOTAL_STR_landed',
 'B_avg_opp_BODY_att',
 'B_avg_opp_BODY_landed',
 'B_avg_opp_CLINCH_att',
 'B_avg_opp_CLINCH_landed',
 'B_avg_opp_DISTANCE_att',
 'B_avg_opp_DISTANCE_landed',
 'B_avg_opp_GROUND_att',
 'B_avg_opp_GROUND_landed',
 'B_avg_opp_HEAD_att',
 'B_avg_opp_HEAD_landed',
 'B_avg_opp_KD',
 'B_avg_opp_LEG_att',
 'B_avg_opp_LEG_landed',
 'B_avg_opp_PASS',
 'B_avg_opp_REV',
 'B_avg_opp_SIG_STR_att',
 'B_avg_opp_SIG_STR_landed',
 'B_avg_opp_SIG_STR_pct',
 'B_avg_opp_SUB_ATT',
 'B_avg_opp_TD_att',
 'B_avg_opp_TD_landed',
 'B_avg_opp_TD_pct',
 'B_avg_opp_TOTAL_STR_att',
 'B_avg_opp_TOTAL_STR_landed',
 'B_Height_cms',
 'B_Reach_cms',
 'B_Weight_lbs',
 'R_avg_BODY_att',
 'R_avg_BODY_landed',
 'R_avg_CLINCH_att',
 'R_avg_CLINCH_landed',
 'R_avg_DISTANCE_att',
 'R_avg_DISTANCE_landed',
 'R_avg_GROUND_att',
 'R_avg_GROUND_landed',
 'R_avg_HEAD_att',
 'R_avg_HEAD_landed',
 'R_avg_KD',
 'R_avg_LEG_att',
 'R_avg_LEG_landed',
 'R_avg_PASS',
 'R_avg_REV',
 'R_avg_SIG_STR_att',
 'R_avg_SIG_STR_landed',
 'R_avg_SIG_STR_pct',
 'R_avg_SUB_ATT',
 'R_avg_TD_att',
 'R_avg_TD_landed',
 'R_avg_TD_pct',
 'R_avg_TOTAL_STR_att',
 'R_avg_TOTAL_STR_landed',
 'R_avg_opp_BODY_att',
 'R_avg_opp_BODY_landed',
 'R_avg_opp_CLINCH_att',
 'R_avg_opp_CLINCH_landed',
 'R_avg_opp_DISTANCE_att',
 'R_avg_opp_DISTANCE_landed',
 'R_avg_opp_GROUND_att',
 'R_avg_opp_GROUND_landed',
 'R_avg_opp_HEAD_att',
 'R_avg_opp_HEAD_landed',
 'R_avg_opp_KD',
 'R_avg_opp_LEG_att',
 'R_avg_opp_LEG_landed',
 'R_avg_opp_PASS',
 'R_avg_opp_REV',
 'R_avg_opp_SIG_STR_att',
 'R_avg_opp_SIG_STR_landed',
 'R_avg_opp_SIG_STR_pct',
 'R_avg_opp_SUB_ATT',
 'R_avg_opp_TD_att',
 'R_avg_opp_TD_landed',
 'R_avg_opp_TD_pct',
 'R_avg_opp_TOTAL_STR_att',
 'R_avg_opp_TOTAL_STR_landed',
 'R_Height_cms',
 'R_Reach_cms',
 'R_Weight_lbs',
 'B_age',
 'R_age',
 'weight_diff_red-blue',
 'height_diff_red-blue']

###  We have to drop some unnecessary columns

In [284]:
df1.drop(columns=[ "R_fighter","B_fighter", "Referee", "date","location","R_draw","B_draw","no_of_rounds","R_wins","B_wins",
                  "R_losses","B_losses","B_total_title_bouts","R_total_title_bouts"], inplace=True)

In [290]:
df1.drop(columns=[ "R_total_rounds_fought","B_total_rounds_fought","R_total_time_fought(seconds)","B_total_time_fought(seconds)",
                  "R_longest_win_streak","B_longest_win_streak","R_current_lose_streak","B_current_lose_streak"], inplace=True)

In [293]:
df1.drop(columns=['R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO',
                  'R_win_by_Submission','R_win_by_TKO_Doctor_Stoppage',"B_current_win_streak",'B_win_by_Decision_Majority',
                  'B_win_by_Decision_Split','B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission',
                  'B_win_by_TKO_Doctor_Stoppage', ], inplace=True)

In [296]:
df1.drop(columns=["R_current_win_streak" ], inplace=True)

In [299]:
df1.drop(columns=['R_Stance','B_Stance'], inplace=True)

In [301]:
df1.shape

(3360, 109)

In [302]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[["Strawweight","Women's Strawweight", "Flyweight","Women's Flyweight", "Bantamweight","Women's Bantamweight","Featherweight","Women's Featherweight",
                                      "Lightweight","Welterweight","Middleweight","Light Heavyweight","Heavyweight","Open Weight","Catch Weight"]],dtype=np.int8)
df1['weight_class'] = encoder.fit_transform(df1['weight_class'].values.reshape(-1, 1))

In [304]:
df1.title_bout=[0 if value == False else 1 for value in df1["title_bout"]]  # 0=False , 1=True

In [307]:
df1.drop(df1[df1.Winner == "Draw"].index, inplace=True)

In [311]:
df1["Winner"]= [0 if value == "Blue" else 1 for value in df1["Winner"]] # 1=Red, 0=Blue

In [313]:
df1.head()

,Winner,title_bout,weight_class,B_avg_BODY_att,B_avg_BODY_landed,B_avg_CLINCH_att,B_avg_CLINCH_landed,B_avg_DISTANCE_att,B_avg_DISTANCE_landed,B_avg_GROUND_att,...,R_avg_opp_TD_pct,R_avg_opp_TOTAL_STR_att,R_avg_opp_TOTAL_STR_landed,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age,weight_diff_red-blue,height_diff_red-blue
0,1,1,4,9.200000,6.000000,0.200000,0.000000,62.600000,20.600000,2.600000,...,0.050000,110.500000,43.300000,162.56,162.56,135.0,31.0,32.0,0.0,-5.08
1,1,1,3,14.600000,9.100000,11.800000,7.300000,124.700000,42.100000,2.400000,...,0.147143,158.142857,82.285714,165.10,167.64,125.0,32.0,31.0,0.0,-2.54
2,1,0,8,15.354839,11.322581,6.741935,4.387097,84.741935,38.580645,5.516129,...,0.131333,102.133333,38.600000,180.34,193.04,155.0,36.0,35.0,0.0,-5.08
3,0,0,4,17.000000,14.000000,13.750000,11.000000,109.500000,48.750000,13.000000,...,0.000000,115.125000,48.875000,162.56,172.72,135.0,26.0,29.0,0.0,-7.62
4,0,0,12,17.000000,14.500000,2.500000,2.000000,201.000000,59.500000,0.000000,...,0.000000,60.500000,27.750000,187.96,190.50,264.0,32.0,26.0,14.0,7.62

In [314]:
df1.to_csv('data/modeling_numeric.csv',index=False)